### ISSUE TITLE
task list

### ISSUE THREAD

**Issue by khibma** [NatureServe-Canada/EBARReviewer#3]
division of tasks

Hanna
- [x]  3. Add MigrantStatus to Review but comment out 
- [x] 4. Support multiple RangeMap Versions/Stages by adding 0/1 field "IncludeInEBARReviewer" to RangeMap and View and selecting only 1s 
- [x]  5. Multi-select ecoshapes for review, with UI changes including mode toggle and integrated add/remove panel, with appropriate warnings 
- [x] 7. For overall review, support both Save and Submit (fill DateCompleted, prevents further edits) 
- [ ] 8. Multi-lingual UI support 
- [x]  9. Remember latest selected basemap per user 
- [x] 10. Fill DateStarted on first edit 

Kevin
- [x] 1. On Ecoshape select, show Presence (decoded) and Notes from RangeMapEcoshape 
- [x] 2. Disable identify pop-up on Major Lakes and Rivers click 

Undecided
- [x] 6. Display of underlying shareable point, line and polygon data (probably on Ecoshape select for performance reasons)

**Comment by khibma** [comment]
Items 4 and 9 addressed by Pull Request #4

**Comment by khibma** [comment]
As of Jan 30, highest priory items:

(7). For overall review, support both Save and Submit (fill DateCompleted, prevents further edits)

(10). Fill DateStarted on first edit

**Comment by khibma** [comment]
5,6,7,8 covered by Version A-D issues
